name: 'evox'
version: '0.1.0'
build:
  packages:
    evox:
    apps:
  bits:
  cppflags:
    - -g
    - -std=c++11
    - -O2
test:
  bits:
    cpputest: 'latest'
  packages:
    tests/helpers:
  cppflags:
    - -g
    - -std=c++11
targets:
  default:
    main: 'main.cpp'
